MVCProject/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCProject.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCProject/Controllers/LoginController.cs
using AutoMapper;
using BLL.Repository;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using MVCProject.Entities.Concrete;
using MVCProject.Models;
using MVCProject.Repository.Abstract;
using MVCProject.Validations;
using System;

namespace MVCProject.Controllers
{
    public class LoginController : Controller
    {
        IValidator<EmployeeLoginVM> validator;
        IEmployeeRepository employeeRepository;
        IMapper mapper;
        public LoginController(IValidator<EmployeeLoginVM> validator, IEmployeeRepository employeeRepository, IMapper map)
        {
            this.validator = validator;
            this.employeeRepository = employeeRepository;
            this.mapper = map;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(EmployeeLoginVM userVm)
        {
            Employee employee = mapper.Map<Employee>(userVm);
            Employee employeeLogin = employeeRepository.GetEmployeeByMailAndPassword(userVm.Mail, userVm.Password);

            if (!ModelState.IsValid)
            {
                return View("Index", userVm);
            }
            if (employeeLogin is null)
            {
                ViewBag.Info = "Hatali";
                return View("Index", userVm);
            }
            return RedirectToAction("Index", "UserHome");
        }

        public IActionResult IsPeronExistControl(EmployeeLoginVM loginVM)
        {
            Employee employee = employeeRepository.GetEmployeeByMailAndPassword(loginVM.Mail, loginVM.Password);
            if (employee is not null)
            {
                HttpContext.Session.SetString("Id", $"{employee.Id}");
                return Json(employee.Id);
            }
            return Json("fail");
        }

    }
}

MVCProject/Controllers/RegisterController.cs
using AutoMapper;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using MVCProject.Entities.Concrete;
using MVCProject.Extensions;
using MVCProject.Models;
using MVCProject.Repository.Abstract;

namespace MVCProject.Controllers
{
    public class RegisterController : Controller
    {
        IEmployeeRepository EmployeeRepository;
        ICompanyRepository CompanyRepository;
        IValidator<EmployeeRegisterVM> empValidator;
        IValidator<CompanyRegisterVM> comValidator;
        IMapper mapper;
        public RegisterController(IEmployeeRepository empRep , ICompanyRepository comRep , IMapper mapper , IValidator<EmployeeRegisterVM> empValidator , IValidator<CompanyRegisterVM> comValidator )
        {
            EmployeeRepository = empRep;
            CompanyRepository = comRep; 
            this.empValidator = empValidator;
            this.comValidator = comValidator;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(EmployeeCompanyVM ecVM)
        {
            if (!ModelState.IsValid)
            {
            
                return NoContent(); 
            }
            var company =mapper.Map<Company>(ecVM.Company);
            bool isAddedCom =CompanyRepository.Add(company);
            var employee =mapper.Map<Employee>(ecVM.Employee);
            employee.CompanyId = company.Id;
            employee.EmployeeType = Entities.Enums.EmployeeType.Admin;
            bool isAddedEmp=EmployeeRepository.Add(employee);

            if(isAddedCom && isAddedEmp)
            {
                //Thread.Sleep(10000);
                //return RedirectToAction("Index", "Login");
                return NoContent();
            }
           return NoContent();
        }
    }
}

MVCProject/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCProject.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VStorageManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" type="image/png" href="https://i.hizliresim.com/y483xrx.png">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="m-4">
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow mb-3 rounded-3">
            <div class="container-fluid mx-4">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://i.hizliresim.com/c5gqcgb.png" height="80" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-3 nav-elements" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-3 nav-elements" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-3 nav-elements" asp-area="" asp-controller="Collaborations" asp-action="Index">Collaborations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-3 nav-elements" asp-area="" asp-controller="SampleStorages" asp-action="Index">Sample Storages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-3 nav-elements" asp-area="" asp-controller="Contact" asp-action="index">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <a class="btn btn-light text-primary fs-6 mx-2 nav-btn fw-bold" asp-controller="Login" asp-action="index">Login</a>
                        <a class="btn btn-light text-primary fs-6 mx-2 nav-btn fw-bold" asp-controller="Register" asp-action="index">Register</a>
                    </div>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="bg-primary mx-4 px-4 rounded-3">

            <div class="d-flex flex-wrap justify-content-between align-items-center border-top">
                <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        <svg class="bi" width="30" height="40">
                            <use xlink:href="#bootstrap"></use>
                        </svg>
                    </a>
                    <p class="mb-3 mb-md-0 text-white">This site is made by Enes Kurt & Ömer İlbey İkiz.</p>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Services" asp-action="Index">
                            Services
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Collaborations" asp-action="Index">
                            Collaborations
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="SampleStrorages" asp-action="Index">
                            Sample Strorages
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Contact" asp-action="index">
                            Contact
                        </a>
                    </li>

                </ul>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-muted" href="https://github.com/Enes-Kurt" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/3291/3291695.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="https://www.linkedin.com/in/eneskurt/" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/3536/3536505.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="https://www.instagram.com/enesskurtt96/" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/1409/1409946.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VStorageManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" type="image/png" href="https://i.hizliresim.com/y483xrx.png">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="m-4">
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow mb-3 rounded-3">
            <div class="container-fluid mx-4">
                <a class="navbar-brand" asp-area="" asp-controller="UserHome" asp-action="Index">
                    <img src="https://i.hizliresim.com/c5gqcgb.png" height="80" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-2 nav-elements" asp-area="" asp-controller="UserHome" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-2 nav-elements" asp-area="" asp-controller="Storages" asp-action="Index">Storages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-2 nav-elements" asp-area="" asp-controller="Management" asp-action="Index">Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-2 nav-elements" asp-area="" asp-controller="SampleStrorages" asp-action="Index">Sample Strorages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 mx-2 nav-elements" asp-area="" asp-controller="Contact" asp-action="index">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <a class="btn btn-light text-primary fs-6 mx-2 nav-btn fw-bold" href="">Profile</a>
                        <a class="btn btn-light text-primary fs-6 mx-2 nav-btn fw-bold" href="">Log out</a>
                    </div>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="bg-primary mx-4 px-4 rounded-3">

            <div class="d-flex flex-wrap justify-content-between align-items-center border-top">
                <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        <svg class="bi" width="30" height="40">
                            <use xlink:href="#bootstrap"></use>
                        </svg>
                    </a>
                    <p class="mb-3 mb-md-0 text-white">This site is made by Enes Kurt & Ömer İlbey İkiz.</p>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex ">
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Storages" asp-action="Index">
                            Storages
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="ToDoList" asp-action="Index">
                            To Do List
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="SampleStrorages" asp-action="Index">
                            Sample Strorages
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-light text-decoration-none" asp-controller="Contact" asp-action="index">
                            Contact
                        </a>
                    </li>

                </ul>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-muted" href="https://github.com/Enes-Kurt" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/3291/3291695.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="https://www.linkedin.com/in/eneskurt/" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/3536/3536505.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="https://www.instagram.com/enesskurtt96/" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/512/1409/1409946.png" class="bi" width="30" height="30"></img>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>